name: Secure Android CI/CD

permissions:
  actions: write

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle  # Caches Gradle dependencies for faster builds

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Restore Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Install Dependencies
        run: ./gradlew dependencies --no-daemon

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Security Linting
        run: ./gradlew lint

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Unit Tests
        run: ./gradlew test

  release:
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4  # Updated from v3 to v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk

  notify:
    runs-on: ubuntu-latest
    needs: release
    if: failure()

    steps:
      - name: Notify on Failure
        run: echo "Build failed! Check logs for details."